### ISSUE TITLE
Strimmer's shrinkage discriminant analysis

### ISSUE THREAD

**Issue by bbuchsbaum** [tidymodels/discrim#18]
## Feature

The R package "sda" [1] implements shrinkage discriminant analysis which is designed for high-dimensional data [2]. A major advantage of this technique is that by default it optimizes the shrinkage parameter on the training data (using James-Stein shrinkage estimator) and therefore performs well without parameter tuning. In neuroimaging analysis it is common to run thousands of machine learning models over successive "searchlight" windows covering the brain and therefore parameter tuning for every model is not feasible. I have also found sda to perform very well for noisy and highly correlated data. It's also very fast because it uses computational tricks to speed up covariance estimation. So I think "sda" would be a nice addition to the "discrim" package.

I created a bare bones implementation of sda for parsnip here:

https://github.com/bbuchsbaum/shrinkagediscrim

[1] https://cran.r-project.org/web/packages/sda/index.html
[2] Ahdesmaki, M., Zuber, V., & Strimmer, K. (2013). Shrinkage discriminant analysis and CAT score variable selection.

**Comment by topepo** [comment]
I'm a fan of this work so I'd be happy to include it. I considered it originally too. 

IIRC this would affect linear discriminant analysis model only?  If that's the case, then we should include it as an engine to a new `discrim_linear()` method.

**Comment by bbuchsbaum** [comment]
Yes, I think sda is linear. I would also consider it "regularized", although it is slightly different than the existing "linear_regularized" implementations.

**Comment by topepo** [comment]
There are a lot of ways to conduct regularization. Historically, Regularized discriminant analysis corresponds to a method to combine LDA and QDA [(pdf)](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.382.2682&rep=rep1&type=pdf) . 

The main question is what the arguments to `discrim_linear()` would be. I think that an option for `regularization_method`.

I might want to resurrect the methods in the [`sparsediscrim`](https://cran.r-project.org/web/packages/sparsediscrim/index.html) package, which has a lot of other methods. 

Suggestions are welcome. I'll start scoping this out in a few days.

**Comment by topepo** [comment]
closed by #28
