### ISSUE TITLE
Re-licensing discrim 🌟

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/discrim#22]
We are systematically re-licensing tidymodels packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all non-RStudio [contributors](https://github.com/tidymodels/discrim/graphs/contributors). 

@EmilHvitfeldt, that is just you! 😄 Would you permit us to re-license discrim with the MIT license? If so, please comment "I agree" below.

* [x] [@EmilHvitfeldt](https://github.com/tidymodels/discrim/commits?author=EmilHvitfeldt)  

Also, would you like to give blanket permission for re-licensing other tidymodels packages to MIT? If so, please also indicate that here. (I won't have to include you in other requests this way.)

**Comment by EmilHvitfeldt** [comment]
I agree 🦀
