### ISSUE TITLE
Why is `naive_Bayes()` not lowercase

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/discrim#32]
As the title says. Why is the name of this function not fully lowercase like most other parsnip model specifications? Is it because Bayes is a proper noun?

**Comment by juliasilge** [comment]
We have been at least moderately consistent about this across tidymodels, for example with `step_YeoJohnson()`, `step_BoxCox()`, etc.

**Comment by EmilHvitfeldt** [comment]
True, alright then it doesn't seem like that big of a deal 😄
