### ISSUE TITLE
Many of the tidymodels/discrim documentation websites aren't accessible anymore

### ISSUE THREAD

**Issue by deschen1** [tidymodels/discrim#39]
E.g. https://discrim.tidymodels.org/reference/details_naive_Bayes_naivebayes.html throws a 404 error (so do many others).

**Comment by EmilHvitfeldt** [comment]
Hello @deschen1! thank for bringing this to our attention. This is an unfortunate side-effect of our effort to move the engine specific documentation to {parsnip}
https://github.com/tidymodels/parsnip/pull/631

This will hopefully be fixed shortly!
