### ISSUE TITLE
Adding fastNaiveBayes as engine to naive_bayes()

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/discrim#5]
Would you be open for a PR adding https://github.com/mskogholt/fastNaiveBayes as an engine to `naive_bayes()`?

**Comment by topepo** [comment]
I'm not a fan of this. It is only fast because it pushes the work on the user. I think that we would end up fielding issues in our repos because it deliberately operates differently than most packages.

**Comment by EmilHvitfeldt** [comment]
Alright, sounds reasonable.

**Comment by EmilHvitfeldt** [comment]
what about the `naive_bayes()` from **naivebayes** package? That one was available in **caret**.

https://github.com/majkamichal/naivebayes

**Comment by topepo** [comment]
That looks fine. Should I or do you want to take a shot at it?

**Comment by EmilHvitfeldt** [comment]
I can take a shot at it
